const messages = [
    "Eres mi todo... ❤️",
    "Eres mi sueño hecho realidad... 💫",
    "Te pienso siempre... 💭",
    "Contigo todo es perfecto... 🌟",
    "Eres mi inspiración... 💖",
    "Eres mi refugio... 🏠",
    "Eres mi amor eterno... 💕",
    "Eres mi paz interior... 🌸",
    "Contigo todo es mejor... 🌈",
    "Eres mi amor verdadero... 💞",
    "Eres tan linda y tierna... 💖",
    "Eres mi sueño cumplido... 🌠",
    "Eres mi mundo... 🌍",
    "Eres perfecta... 💎",
    "Eres hermosa... 🌹",
    "Eres única... 🦄",
    "Eres encantadora... ✨",
    "Eres preciosa... 🌼",
    "Eres adorable... 💐",
    "Eres maravillosa... 🌺"
];